<a href="https://colab.research.google.com/github/govind527/Pytorch_Practice/blob/main/Pytorch_Practice_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import torch
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)



2.6.0+cu124


In [2]:
scalar=torch.tensor(7)
scalar

tensor(7)

In [3]:
scalar.ndim

0

In [4]:
scalar.item()

7

In [5]:
 vector=torch.tensor([5,6,4])
 vector

tensor([5, 6, 4])

In [6]:
vector.ndim

1

In [7]:
vector.shape

torch.Size([3])

In [8]:
MATRIX=torch.tensor([[4,5],
                     [3,2]])

In [9]:
MATRIX

tensor([[4, 5],
        [3, 2]])

In [10]:
MATRIX.ndim

2

In [11]:
MATRIX[1]

tensor([3, 2])

In [12]:
MATRIX.shape

torch.Size([2, 2])

In [13]:
TENSOR=torch.tensor([[[1,2,3],
                      [3,4,5],
                      [6,5,3],
                      [4,3,3]]])

In [14]:
TENSOR

tensor([[[1, 2, 3],
         [3, 4, 5],
         [6, 5, 3],
         [4, 3, 3]]])

In [15]:
TENSOR.ndim

3

In [16]:
TENSOR.shape

torch.Size([1, 4, 3])

In [17]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 4, 5],
        [6, 5, 3],
        [4, 3, 3]])

In [18]:
random_tensor=torch.rand(3,4)

In [19]:
random_tensor

tensor([[0.5631, 0.9151, 0.7350, 0.8041],
        [0.9297, 0.5095, 0.5428, 0.1920],
        [0.4908, 0.9469, 0.1714, 0.0504]])

In [20]:
random_tensor.ndim

2

In [21]:
random_image_size_tensor=torch.rand(size=(224,224,3))
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [22]:
rntensor=torch.rand(1,3,3)

In [23]:
rntensor

tensor([[[0.3662, 0.6182, 0.1420],
         [0.2395, 0.6355, 0.8627],
         [0.5611, 0.7784, 0.9560]]])

In [24]:
zero_tensor=torch.zeros(size=(3,4))
zero_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [25]:
ones_tensor=torch.ones(size=(3,4))
ones_tensor

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [26]:
ones_tensor.dtype

torch.float32

In [27]:
random_rang=torch.arange(start=2,end=12,step=1)
random_rang


tensor([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [28]:
tensor_like_zeors=torch.zeros_like(input=random_rang)
tensor_like_zeors

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [29]:
newtens=torch.ones_like(input=random_rang)
newtens

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [30]:
float_32=torch.tensor([3.0,4.0],
                          dtype=torch.float32,
                          device=None,
                          requires_grad=False)
float_32

tensor([3., 4.])

In [31]:
float_16=float_32.type(torch.float16)
float_16

tensor([3., 4.], dtype=torch.float16)

In [32]:
float_32*float_16

tensor([ 9., 16.])

In [33]:
some_tensor=torch.rand(3,4).type(torch.float64)
some_tensor

tensor([[0.5848, 0.0821, 0.1011, 0.5394],
        [0.3395, 0.0352, 0.0869, 0.7852],
        [0.2799, 0.7381, 0.0529, 0.2209]], dtype=torch.float64)

In [34]:
print(f"datatype of  tensor: {some_tensor.dtype}")
print(f"shape of  tensor: {some_tensor.shape}")
print(f"devide tensor is on : {some_tensor.device}")

datatype of  tensor: torch.float64
shape of  tensor: torch.Size([3, 4])
devide tensor is on : cpu


### operations

In [35]:
tensor_a=torch.tensor([1,2,3])
tensor_a+10

tensor([11, 12, 13])

In [36]:
a=torch.mul(tensor_a,20)
b=torch.add(tensor_a,20)
c=torch.div(tensor_a,12)
a,b,c

(tensor([20, 40, 60]), tensor([21, 22, 23]), tensor([0.0833, 0.1667, 0.2500]))

In [37]:
v=torch.matmul(tensor_a,tensor_a)
v

tensor(14)

In [38]:
torch.matmul(torch.rand(3,2),torch.rand(2,1))

tensor([[0.0101],
        [0.2433],
        [0.0477]])

In [39]:
A=torch.tensor([[1,2],
                [3,4],
                [5,6]])

B=torch.tensor([[5,6],
                [7,8],
                [8,9]])

torch.matmul(A,B.T)

tensor([[17, 23, 26],
        [39, 53, 60],
        [61, 83, 94]])

### Aggregation

In [40]:
x=torch.arange(0,100,10)

In [41]:
torch.min(x),torch.max(x),torch.mean(x.type(torch.float32)) ### dataype check for mean

(tensor(0), tensor(90), tensor(45.))

In [42]:
x.sum()

tensor(450)

In [43]:
x.argmax(),x.argmin()

(tensor(9), tensor(0))

In [44]:
w=torch.arange(1.,10.)

In [45]:
w,w.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [46]:
w_reshape=w.reshape(1,9)
w_reshape,w_reshape.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [47]:
z=w.view(3,3)
z

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])

In [48]:
w_stack=torch.stack([w,w,w],dim=1)
w_stack

tensor([[1., 1., 1.],
        [2., 2., 2.],
        [3., 3., 3.],
        [4., 4., 4.],
        [5., 5., 5.],
        [6., 6., 6.],
        [7., 7., 7.],
        [8., 8., 8.],
        [9., 9., 9.]])

In [49]:
xx=torch.zeros(2,1,2,1,2)
xx.size()

torch.Size([2, 1, 2, 1, 2])

In [50]:
yy=torch.squeeze(xx)
yy

tensor([[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]])

In [51]:
yy.size()

torch.Size([2, 2, 2])

In [52]:
yy=torch.squeeze(xx,0)
yy.size()

torch.Size([2, 1, 2, 1, 2])

In [53]:
squw=torch.rand(3,1)
squw.size()


torch.Size([3, 1])

In [54]:
squw.squeeze().size()

torch.Size([3])

In [55]:
squw.unsqueeze(dim=1).size()

torch.Size([3, 1, 1])

In [56]:
squw.size()

torch.Size([3, 1])

In [57]:
squw

tensor([[0.0072],
        [0.3172],
        [0.0153]])

In [58]:
squw.permute(1,0)

tensor([[0.0072, 0.3172, 0.0153]])

In [59]:
x_org=torch.rand(size=(224,224,3))

In [60]:
x_org[0,0,0]=233

In [61]:
x_org[0,0,0]

tensor(233.)

In [62]:
x_per=x_org.permute(2,0,1)

In [63]:
x_per[0,0,0]

tensor(233.)

In [64]:
import torch
import pandas as pd
import numpy  as  np
c=torch.arange(1,10,1).reshape(1,3,3)
c,c.ndim

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 3)

In [65]:
c[0][2][2]

tensor(9)

In [66]:
c[0,2,2]

tensor(9)

In [67]:
c[:,:,2]

tensor([[3, 6, 9]])

In [68]:
array=np.arange(1.0,8.0)
tensorr=torch.from_numpy(array)
array.dtype,tensorr.dtype

(dtype('float64'), torch.float64)

In [69]:
cc=torch.arange(1.0,4.) ## default datatype of tensor is float32 while numpy as float64
cc.dtype

torch.float32

In [70]:
cc.numpy()## tensor to numpy

array([1., 2., 3.], dtype=float32)

In [71]:
RANDOM_SEED=42
torch.manual_seed(RANDOM_SEED) ## keep in my this is used for every lines that we will use
z=torch.rand(3,4)
torch.manual_seed(RANDOM_SEED)
y=torch.rand(3,4)
print(z)
print(y)
print(z==y)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


In [72]:
!nvidia-smi

Tue Jul  1 04:09:14 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.15              Driver Version: 550.54.15      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   51C    P8             10W /   70W |       0MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [73]:
torch.cuda.is_available()

True

In [74]:
device="cuda"

In [75]:
torch.cuda.device_count()

1